# Start ExplorViz discovery service version 1.3.0

version: "3.2"
services:

  discovery:
    image: explorviz/explorviz-backend-discovery:1.3.0
    container_name: explorviz-backend-discovery
    ports:
      - "YOUR-DISCOVERY-PORT:8083"
